import {
  AlertTriangle,
  BarChart3,
  BookMarked,
  BookOpen,
  Building2,
  Calendar,
  ClipboardList,
  FolderKanban,
  HeartPulse,
  LayoutDashboard,
  School,
  SearchCheck,
  Settings,
  Shield,
  ShieldCheck,
  Users,
  UtensilsCrossed,
  Wallet,
  Waypoints,
} from 'lucide-react'

export const MODULOS_APP = [
  { modulo: 'dashboard', path: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, secao: 'Visão Geral' },
  { modulo: 'secretaria', path: '/secretaria', label: 'Secretaria', icon: ClipboardList, secao: 'Secretaria' },
  { modulo: 'diario', path: '/diario', label: 'Diário', icon: ClipboardList, secao: 'Pedagógico' },
  { modulo: 'turmas', path: '/turmas', label: 'Turmas', icon: School, secao: 'Pedagógico' },
  { modulo: 'alunos', path: '/alunos', label: 'Alunos', icon: Users, secao: 'Pedagógico' },
  { modulo: 'chamada', path: '/chamada', label: 'Chamada', icon: ClipboardList, secao: 'Pedagógico' },
  { modulo: 'calendario', path: '/calendario', label: 'Calendário', icon: Calendar, secao: 'Pedagógico' },
  { modulo: 'notas', path: '/notas', label: 'Notas', icon: BookOpen, secao: 'Pedagógico' },
  { modulo: 'disciplinas', path: '/disciplinas', label: 'Disciplinas', icon: BookMarked, secao: 'Pedagógico' },
  { modulo: 'ocorrencias', path: '/ocorrencias', label: 'Ocorrências', icon: AlertTriangle, secao: 'Pedagógico' },
  { modulo: 'financeiro', path: '/financeiro', label: 'Financeiro', icon: Wallet, secao: 'Administrativo' },
  { modulo: 'projetos', path: '/projetos', label: 'Projetos', icon: FolderKanban, secao: 'Administrativo' },
  { modulo: 'relatorios', path: '/relatorios', label: 'Relatórios', icon: BarChart3, secao: 'Administrativo' },
  { modulo: 'saude', path: '/saude', label: 'Saúde', icon: HeartPulse, secao: 'Operacional' },
  { modulo: 'nutricao', path: '/nutricao', label: 'Nutrição', icon: UtensilsCrossed, secao: 'Operacional' },
  { modulo: 'supervisao', path: '/supervisao', label: 'Supervisão', icon: SearchCheck, secao: 'Operacional' },
  { modulo: 'colegio', path: '/colegio', label: 'Colégio', icon: Building2, secao: 'Operacional' },
  { modulo: 'paesp', path: '/paesp', label: 'PAESP', icon: BarChart3, secao: 'Operacional' },
  { modulo: 'integracoes', path: '/integracoes', label: 'Integrações', icon: Waypoints, secao: 'Operacional' },
  { modulo: 'usuarios', path: '/usuarios', label: 'Usuários', icon: Shield, secao: 'Sistema' },
  { modulo: 'auditoria', path: '/auditoria', label: 'Auditoria', icon: ShieldCheck, secao: 'Sistema' },
  { modulo: 'configuracoes', path: '/configuracoes', label: 'Configurações', icon: Settings, secao: 'Sistema' },
]

export const SECOES_MENU = ['Visão Geral', 'Secretaria', 'Pedagógico', 'Administrativo', 'Operacional', 'Sistema']
